language: python
python:
 - "3.6"

addons:
  apt:
    packages:
      - openjdk-8-jre

branches:
  only:
    - master

install:
 - pip install html5validator

script: 
  # - test -n "$(ls -A htdocs/)"
  - python test.py
  # - test -e ./htdocs/index.html
#  - html5validator --root htdocs/ --also-check-cs
#  - make test 

