language: python
python:
 - "3.6"
addons:
  apt:
    packages:
      - openjdk-8-jre

branches:
  only:
    - master

install:
 - pip install html5validator

script: html5validator --root htdocs/ --also-check-cs
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
