language: python
python:
 - "3.6"
addons:
  apt:
    packages:
      - openjdk-8-jre

branches:
  only:
    - master

install:
 - pip install html5validator

script: html5validator --root htdocs/ --also-check-cs
  - html5validator --root htdocs/ --also-check-cs
  - test -e ./htdocs/index.html
#  - make test 

